php:
    image: akhyarmaulana/shooplegacy
    ports:
        - "80:80"
    links:
        - db
    volumes:
        - ./:/var/www/html/
        - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
        - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
db:
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: apple
    volumes:
        - ./mysql_directory:/var/lib/mysql
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8888:80"
    links:
        - db
redis:
    image: redis
    ports: 
        - "6379:6379"