<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|   http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
$http = 'http' . ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 's' : '') . '://';
$fo = str_replace("index.php","", $_SERVER['SCRIPT_NAME']);
$config['base_url']    = "$http" . $_SERVER['SERVER_NAME'] . "" . $fo;
$config['admin_url']    = $config['base_url'].'admin/';

$config['secure_base_url'] = $config['base_url'];
$config['unsecure_base_url'] = $config['base_url'];
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'            Default - auto detects
| 'PATH_INFO'       Uses the PATH_INFO
| 'QUERY_STRING'    Uses the QUERY_STRING
| 'REQUEST_URI'     Uses the REQUEST_URI
| 'ORIG_PATH_INFO'  Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol'] = 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language'] = 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']      = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']   = 'c';
$config['function_trigger']     = 'm';
$config['directory_trigger']    = 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|   0 = Disables logging, Error logging TURNED OFF
|   1 = Error Messages (including PHP errors)
|   2 = Debug Messages
|   3 = Informational Messages
|   4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'cpk';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'        = the name you want for the cookie
| 'sess_expiration'         = the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'    = Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'     = Whether to encrypt the cookie
| 'sess_use_database'       = Whether to save the session data to a database
| 'sess_table_name'         = The name of the session database table
| 'sess_match_ip'           = Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'    = Whether to match the User Agent when reading the session data
| 'sess_time_to_update'     = how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']     = 'ci_session';
$config['sess_expiration']      = 0;
$config['sess_expire_on_close'] = FALSE;
$config['sess_encrypt_cookie']  = TRUE;
$config['sess_use_database']    = TRUE;
$config['sess_table_name']      = 'ci_sessions';
$config['sess_match_ip']        = FALSE;
$config['sess_match_useragent'] = TRUE;
$config['sess_time_to_update']  = 7200;

// switch session backend to redis for performance
$config['redis_host'] = 'localhost';
$config['redis_port'] = '6379';

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']    = "";
$config['cookie_domain']    = "";
$config['cookie_path']      = "/";
$config['cookie_secure']    = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';

/** SMTP EMAIL SETTINGS **/
$config['email_indoloka'] = 'science.afandi@gmail.com';
$config['email_contact_form'] = 'contact@cipika.com';
$config['email_from'] = 'noreply.cipikastore@gmail.com';
$config['email_admin'] = 'andyajadeh@gmail.com';
$config['protocol'] = 'smtp';
$config['smtp_host'] = 'smtp.googlemail.com';
$config['smtp_port'] = 587;
$config['smtp_user'] = 'noreply.cipikastore@gmail.com';
$config['smtp_pass'] = 'cipika123';
$config['mailtype'] = 'html';
$config['charset'] = 'iso-8859-1';
$config['smtp_crypto'] = 'tls';

/** ID & API_KEY SHIPING JNE**/
$config['username_jne'] = 'CIPIKASTORE';
$config['api_key_jne'] = 'a4a9c2438f1d475582be83a490425a79';

/** MARKUP JNE **/
$config['markup_jne'] = 0;

/** ACCOUNT EMAIL ADMIN **/
$config['bcc_email_merchant_pembelian'][] = 'achmadali1992@yahoo.com';
$config['bcc_email_merchant_pembelian'][] = 'andyajadeh@gmail.com';

/** MINIMAL ORDER **/
$config['minimal_order'] = 5000;
$config['minimal_order_payment_5'] = 1000;
$config['minimal_order_payment_18'] = 1000;

$config['google_analytics_script'] = '';
$config['fb_tracking_script'] = '';
$config['fb_product_tracking_script'] = '';
$config['google_online_sale_conversion'] = '';
$config['google_remarketing_tag'] = '';
$config['google_adwords_conversion_code'] = '';

/** URL API JNE **/
$config['url_api_jne'] = "http://shippingapi.getshoop.com";

/** Account AWB JNE **/
$config['url_api_jne_awb'] = "http://api.jne.co.id:8889";
$config['username_api_jne_awb'] = "CIPIKASTORE";
$config['api_key_jne_awb'] = "a4a9c2438f1d475582be83a490425a79";
  
/** POTONGAN SHIPPING KOTA LAIN (Persen) **/ 
$config['potongan_shipping_kota_lain'] = "0";

//Google API Key untuk gcm_id
$config['GOOGLE_API_KEY'] = 'AIzaSyBU_K97z3VAk8H8hrh9YUEHM2_PCsPW-ow';

//KATEGORI ID
$config['kategori_id_kuliner'] = '30';
$config['kategori_id_fashion'] = '29';
$config['kategori_id_handycraft'] = '31';
$config['kategori_id_makanan'] = '38';

/* FITURE VOUCHER */
$config['LENGTH_CODE_VOUCHER'] = 6;
$config['MAX_TOTAL_USER_GET_VOUCHER'] = 100;//Total Pendaftar yang bisa mendapatkan Voucher Gratis
$config['NOMINAL_VOUCHER'] = 50000; //Value Voucher
$config['NOMINAL_GRAND_TOTAL_USE_VOUCHER'] = 200000; //Total Harga Produk bila akan menggunakan Voucher
$config['ACTIVE_FITUR_VOUCHER'] = true; //Total Harga Produk bila akan menggunakan Voucher
$config['MINIMAL_OUTSTANDING_BALANCE'] = 10000;

/*troubleshoot defect*/
$config['UNHIDE_B2B_MENU'] = true;

$config['tmp_dir'] = '/tmp';

$config['show_channel_navbar'] = true;

/*page register merchant*/
$config['page_register_merchant'] = 11;

/* Customer Service untuk tujuan pengiriman Inbox dari Member */
$config['id_user_customer_service'] = 11;

/* Kode Prefix Order */
$config['prefix_kode_order'] = 'ORD';

/* Merchant Pulsa */
$config['merchant_voucher_reload'][] = '90';
/* ID Store : 200 / 214 (merupakan Merchant Voucher Reload) */
$config['merchant_voucher_reload_vendor'][200] = 'dompetku';
$config['merchant_voucher_reload_vendor'][214] = 'mobilepulsa';

/* New UI 2*/
$config['layout'] = 'ui2';
//$config['layout'] = 'ui2';

$config['layout_ui2.1'] = 'active';

/** ACCOUNT EMAIL ADMIN FEATURE VOUCHER RELOAD**/
$config['bcc_email_admin_voucher_reload'][] = 'admin.cipika@cipika.co.id';
$config['bcc_email_admin_voucher_reload'][] = 'andreas.wibowo@indosat.com';

/** Google Client Analytics key **/
$config['google_clientid'] = '771449858561-5hfnc5847onk43366f59el24ul1h984k@developer.gserviceaccount.com';
$config['google_clientsecret'] = 'dNfwCzyaOfq42ndA3F5itC9W';
$config['google_setdeveloperkey'] = 'AIzaSyCWhbQQb9n_ABq_YNdxAPUrpCjDSgg_XGM';
$config['google_analytics_id'] = '85597118';

$config['merchant_product_software'][] = 532;

$config['captcha_enabled'] = true;
$config['jqzoom_enabled'] = true;

$config['redis_namespace'] = 'cipika:';

$config['matrix_channel'] = 'active';

/* API Mobile V3 */
$config['mobile_secret_key'] = 'cipikamobile123';

/* Netcore Mail */
$config['netcore'] = array(
    'url'       => 'https://api.exacttouch.com/API/mailing/',
    'list_id'   => '1',
    'key'       => 'fe8a046a7e8a699c41e3406caa8d54c5',
);

/** kategori produk voucher indosat **/
$config['kategori_id_voucher_indosat'] = 100;

/* id kategori untuk halaman shopping list*/
$config['shooping_list_category'] = 29;

/* BIN Promo KartuKredit */
$config['bin_promo_kartu_kredit'][] = 'bni';
$config['bin_promo_kartu_kredit'][] = 'mandiri';

/* FITUR VOUCHER */
$config['ACTIVE_FITUR_POINT_REWARDS'] = true;
$config['POINT_REWARDS_RUPIAH'] = 1;
$config['point_reward_kelipatan_transaksi'] = 100000;
$config['point_reward_minimal_redeem'] = 40000;

/* MDR Installment */
$config['mdr_installment_persen'] = 3;
$config['mdr_installment_kredivo'] = 2.3;
$config['mdr_nicepay'] = 3500;
$config['mdr_indomaret'] = 4400;

/* Accesstrade Tracking Tag CIPIKA */
$config['accesstrade_url_tracking'] = "https://cv.accesstrade.co.id/cv.php";
$config['accesstrade_mcn_tracking'] = "f2217062e9a397a1dca429e7d70bc6ca";
$config['accesstrade_resultid_tracking'] = "3";

$config['limit_kategori_indosat'] = array(225, 223);

/* Nomor prefix HP Indosat  */
$config['isat_prefix_phone'][] = '+62814';
$config['isat_prefix_phone'][] = '+62815';
$config['isat_prefix_phone'][] = '+62816';
$config['isat_prefix_phone'][] = '+62855';
$config['isat_prefix_phone'][] = '+62856';
$config['isat_prefix_phone'][] = '+62857';
$config['isat_prefix_phone'][] = '+62858';

/* Indosat Freedom Combo Product ID */
$config['indosat_freedom_combo_product_id'][] = 42967;
$config['indosat_freedom_combo_product_id'][] = 42965;
$config['indosat_freedom_combo_product_id'][] = 42959;
$config['indosat_freedom_combo_product_id'][] = 42958;
$config['indosat_freedom_combo_product_id'][] = 19585;
$config['indosat_freedom_combo_product_id'][] = 5008;

//$config['testerIndomaretUser'] = "587";

/* Product Persib */
$config['PERSIB_card_id'][] = 5009;
$config['PERSIB_card_id_galeri'][] = 5009;
$config['PERSIB_store_user_id'][] = 589000;
$config['PERSIB_ftp_hostname'] = '114.4.66.117';
$config['PERSIB_ftp_username'] = 'persib';
$config['PERSIB_ftp_password'] = 'p3rs1bC1pik4';
$config['PERSIB_ftp_homedir'] = '';
$config['PERSIB_mail_partner'] = 'sun.alkunam@gmail.com,sunardi.wijayanto@indosat.com'; // fwd,dompetku,im3,persib_logistics
$config['PERSIB_mail_galeriHO'] = 'elbodonk2014@gmail.com'; 
$config['PERSIB_renewal_product_case_1'] = 5268;
$config['PERSIB_renewal_product_case_2'] = 5269;
$config['PERSIB_renewal_product_case_3'] = 5270;
$config['PERSIB_renewal_product_case_4'] = 5271;
$config['PERSIB_renewal_product_case_5'] = 5277;
$config['PERSIB_renewal_product'][] = 5268;
$config['PERSIB_renewal_product'][] = 5269;
$config['PERSIB_renewal_product'][] = 5270;
$config['PERSIB_renewal_product'][] = 5271;
$config['PERSIB_renewal_product'][] = 5277;

$config['PERSIB_mail_partner_renewal_cetak'] = 'almais.tandung@indosatooredoo.com, euis.fitriah@indosatooredoo.com, kanton.kulaga@indosatooredoo.com';
$config['PERSIB_mail_partner_renewal_alldata'] = 'membership@persib.co.id, dewi.karya@indosatooredoo.com, firdaus.pratama@indosatooredoo.com, yetie@persib.co.id, Shandy@persib.co.id, sunardi.wijayanto@indosat.com, heidi.handayani@fwd.com, mohamad.irpan@fwd.com';

$config['canvasser_sisa_voucher_hangus'] = 25000; 

$config['canvasser_store_voucher_user_id'][] = 589;
$config['bookmate_store_voucher_user_id'][] = 689;
$config['persib_ticket_store_user_id'][] = 690;

/* Hompage cache */
$config['is_active_homepage_cache'] = false;
$config['slug_seo_url'] = TRUE;

// /* indomaret -> cipika ftp */
$config['indomaret_ftp_host'] = '114.4.66.117';
$config['indomaret_ftp_port'] = '21';
$config['indomaret_ftp_username'] = 'indomaret';
$config['indomaret_ftp_password'] = '1nd0m4r3tftp';
$config['indomaret_ftp_remote_dir'] = 'indomaret';
$config['indomaret_ftp_local_dir'] = 'data/indomaret_ftp';

/* PERSIB ticket  */
$config['additional_fee_nonmember'] = 5000;
// $config['PERSIB_ticket_id'][] = 5017;
// $config['PERSIB_ticket_id'][] = 5018;

/* Program Promo Diskon Cipika - Dompetku */
$config['id_program_diskon_dompetku'] = 0;
$config['url_program_diskon_dompetku'] = '';
$config['nama_program_dompetku'] = '';

$config['show_test_pad'] = false;
$config['show_rekomendasi_wholesale'] = true;
$config['show_rekomendasi_gadget'] = true;
$config['show_rekomendasi_brands'] = true;
$config['show_rekomendasi_home_entertainment'] = true;
$config['show_rekomendasi_otomotif'] = false;
$config['show_rekomendasi_lifestyle'] = true;
$config['show_shortcut'] = false;

/* PERSIB ticket  */
$config['additional_fee_nonmember'] = 5000;
//$config['url_persib_login'] = 'http://iips2016.com/cipika_persib_login.php';
$config['url_persib_login'] = 'http://persib.co.id/api/cipika_persib_login.aspx';
//$config['url_persib_login'] = 'http://103.238.138.101/api/cipika_persib_login.aspx';

/* Sold Out Notification Config */
$config['stok_limit_notification'] = 0;
$config['sold_out_email_filter'] = array(
    'akhyar@pangeranweb.com',
    'ali@firzil.co.id'
);

// Development
$config['id_kategori_new'][] = 167; // Voucher Belanja
$config['id_kategori_new'][] = 168; // Tiket

/* Cod Fee */
$config['cod_fee_persen'] = 2.8;

/* Sitemap*/
$sitemap[] = array(
        'id' => 12,
        'channel_name' => 'handphone', 
        'display_name' => 'Handphone',
        'slug' => 'handphone',
        'submenu' => array(
                        array(
                            'id' => 29,
                            'display_name' => 'Jenis handphone',
                            'slug' => 'jenishandphone'
                        ),
                        array(
                            'id' => 31,
                            'display_name' => 'Aksesoris Handphone',
                            'slug' => 'aksesorishandphone'
                        )
                )
        );

$sitemap[] = array(
        'id' => 12,
        'channel_name' => 'komputer', 
        'display_name' => 'Komputer',
        'slug' => 'komputer',
        'submenu' => array(
                        array(
                            'id' => 32,
                            'display_name' => 'Laptop',
                            'slug' => 'laptop'
                        )
                )
        );

$config['sitemap'] = $sitemap;

$config['limit_kategori_indosat'] = array(225, 223);

// list merchant grab
$config['grap_demo_start'] = '2016-06-29 12:00';
$config['grap_demo_end']   = '2016-06-31 12:00';
$config['grap_merchant'] = array(277);
$config['grab_api_key'] = '';
$config['grab_are_prop'] = array(5);
$config['grab_enable'] = TRUE;
// Production
// $config['id_kategori_new'][] = 245; // Voucher Belanja
// $config['id_kategori_new'][] = 247; // Tiket

/** URL API RPX **/ 
$config['url_api_rpx'] = $config['base_url']."cart";

/** Account AWB RPX **/
$config['url_api_rpx_awb'] = "http://api.rpxholding.com/wsdl/rpxwsdl.php?wsdl";
$config['username_api_rpx_awb'] = "cipika"; //cipikadev
$config['password_api_rpx_awb'] = "cipika"; //cipikadev
$config['account_number_api_rpx_awb'] = "800048699"; //???

/** MARKUP RPX **/ 
$config['markup_rpx'] = 0;

//$config['testerRPXMerchantUser'] = 390;
$config['originRPXAktif'] = array(51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69);
$config['kurirHighlight'] = array('RPX');
$config['originRPXAktif'] = array();

$config['merchant_auto_accept'] = array(113928, 120544, 117870, 123081, 116818, 589, 600);

$config['mobo_umb_userid_channel'] = 600;

$config['mobo_web_thirdparty_id']       = 'CipikaSYS';
$config['mobo_web_password']            = 'pg7JSnZOvd5PP8BnV3B5sQ==';
$config['mobo_web_security_credential'] = '66VDaQKzLxFgBJoalJeW/w==';
$config['mobo_web_initiator_identifier'] = 'CipikaOperator';
$config['mobo_web_wsdl']       = 'https://mobo.indosatooredoo.com:8081/payment/services/SYNCAPIRequestMgrService';
$config['merchant_cipika_no_send_mail_sms'] = array(117870); // merchant internal cipika

$config['stat_page_patch'] = '02. lazyload';

$config['mobo_admin_user'] = array(1);

$config['temankredit_non_it_kategori'] = array(126);
$config['temankredit_it_kategori'] = array(136);
$config['temankredit_gadget_kategori'] = array(69);

$config['priority_cicilan'] = 'Teman Kredit';

$config['paymentSanityTest'] = array();
$config['accountSanityTest'] = array();
$config['mdr_installment_kredivo'] = 2.3;

$config['sanity_adira'] = array();
$config['adira_kategori_gadget'] = array(69, 139);
$config['adira_kategori_elektronik'] = array(150,140);
$config['adira_id_user'] = 595;
$config['adira_product'] = (object) array(
    'g50' => 5042,
    'g70' => 5043,
    'g85' => 5044,
    'e40' => 5045,
    'e75' => 5046,
    'e85' => 5047
);
$config['adira_gadget_50'] = 5042;
$config['adira_gadget_70'] = 5043;
$config['adira_gadget_85'] = 5044;

$config['merchant_shipper'] = array(
);

/* ---End of file config.php */
/* Location: ./application/config/config.php */
